### ISSUE TITLE
display proper error message when module.exports is missing in controller

### ISSUE THREAD

**Issue by madhusudhand** [madhusudhand/donode#28]
error:

/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/helpers/route-helper.js:139
      this._controllers[controllerKey] = new ControllerClass();
                                         ^

TypeError: ControllerClass is not a constructor
    at RouteHelper._processRoute (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/helpers/route-helper.js:139:42)
    at RouteHelper._processRouteConfig (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/helpers/route-helper.js:79:30)
    at RouteHelper.collectRoutes (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/helpers/route-helper.js:58:10)
    at Router.collectRoutes (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/router.js:43:32)
    at Server.create (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/node_modules/donode/lib/server.js:34:17)
    at Object.<anonymous> (/Users/madhusudhanad/madhu/os/donode-cli/blueprints/v1/app.js:8:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by madhusudhand** [comment]
1.0.0-beta.3
